FROM node:24-slim

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
RUN corepack enable
RUN corepack yarn install --immutable

COPY tsconfig.json .
COPY src ./src

EXPOSE 3000

CMD ["corepack", "yarn", "dev"]
